In [3]:
import numpy as np
import time

In [17]:
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [18]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c = b[2:7:2]
c

array([2, 4, 6])

In [20]:
print(-b)
print(np.sum(b))
print(np.mean(b))
print(np.std(b))

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
45
4.5
2.8722813232690143


In [22]:
def my_dot(a,b):
	x = 0
	for i in range(a.shape[0]):
		x += (a[i] * b[i])
	return x

24


In [28]:
np.random.seed(1)
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f"time: {(toc-tic)*1000:.4f}")

tic = time.time()
d = np.dot(a,b)
toc = time.time()
print(f"np.dot time: {(toc-tic)*1000:.4f}")

time: 222.4250
np.dot time: 0.8521


In [30]:
a = np.arange(6).reshape(-1,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])